In [6]:
import gym
import numpy as np

env = gym.make('FrozenLake-v0')

#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .85
y = .99
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

[2017-01-03 21:12:12,604] Making new env: FrozenLake-v0


In [7]:
print "Score over time: " +  str(sum(rList)/num_episodes)

Score over time: 0.663


In [8]:
print "Final Q-Table Values"
print Q

Final Q-Table Values
[[  7.02998890e-01   2.69152799e-02   1.69610612e-02   1.36628758e-02]
 [  3.84412187e-03   2.90649820e-04   4.78796297e-03   6.41831002e-01]
 [  5.48909917e-01   4.26745068e-03   2.21161692e-03   1.30502535e-02]
 [  1.04244370e-02   1.99985605e-03   7.42274942e-03   0.00000000e+00]
 [  5.31952488e-01   8.47994293e-04   4.41056338e-03   3.26624124e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  2.11952441e-02   3.96926402e-07   2.27312794e-04   1.53396188e-05]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  4.21908543e-03   2.21544037e-04   5.84688769e-03   8.45937379e-01]
 [  0.00000000e+00   9.55950185e-01   2.22460369e-03   6.58042552e-03]
 [  8.30014118e-01   0.00000000e+00   2.89687492e-03   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.81974649e-02   1.60936875e-02   9.89065419e-01   0