In [2]:
import gym
import numpy as np

env = gym.make('FrozenLake-v0')

#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
# Set learning parameters
lr = .85
y = .99
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

[2017-01-03 21:09:44,020] Making new env: FrozenLake-v0


In [3]:
print "Score over time: " +  str(sum(rList)/num_episodes)

Score over time: 0.5955


In [4]:
print "Final Q-Table Values"
print Q

Final Q-Table Values
[[  6.53264766e-01   7.65371084e-03   1.54895645e-02   4.60796792e-03]
 [  2.02697701e-03   9.19223802e-04   5.96069298e-04   6.13295114e-01]
 [  3.92079296e-01   2.53780991e-03   5.57774482e-04   6.71558161e-04]
 [  0.00000000e+00   2.94100878e-03   5.57774482e-04   6.57199523e-04]
 [  6.78598990e-01   6.42909094e-05   2.13102363e-04   1.15868136e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  7.48903273e-02   5.46783075e-06   4.98855757e-05   1.91575752e-09]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.19192646e-03   3.98001020e-06   5.63222303e-04   4.38121582e-01]
 [  1.95119288e-03   8.01681319e-01   4.65841460e-04   1.48852381e-04]
 [  4.58901014e-01   1.67738880e-04   8.74213652e-04   3.70025941e-04]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   9.67034693e-01   0